# Definimos los servicios necesarios para la configuración del stack de Elastic.
services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
    user: "0"
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;
        if [ ! -f config/certs/ca.zip ]; then
          echo "Creating CA";
          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
          unzip config/certs/ca.zip -d config/certs;
        fi;
        if [ ! -f config/certs/certs.zip ]; then
          echo "Creating certs";
          echo -ne \
          "instances:\n"\
          "  - name: es01\n"\
          "    dns:\n"\
          "      - es01\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: kibana\n"\
          "    dns:\n"\
          "      - kibana\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          "  - name: fleet-server\n"\
          "    dns:\n"\
          "      - fleet-server\n"\
          "      - localhost\n"\
          "    ip:\n"\
          "      - 127.0.0.1\n"\
          > config/certs/instances.yml;
          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
          unzip config/certs/certs.zip -d config/certs;
        fi;
        echo "Setting file permissions"
        chown -R root:root config/certs;
        find . -type d -exec chmod 750 \{\} \;;
        find . -type f -exec chmod 640 \{\} \;;
        echo "Waiting for Elasticsearch availability";
        until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
        echo "Setting kibana_system password";
        until curl -s -X POST --cacert config/certs/ca/ca.crt -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
        echo "All done!";
      '
    healthcheck:
      test: [ "CMD-SHELL", "[ -f config/certs/es01/es01.crt ]" ]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - elastic_network

  es01:
    # Nodo principal de Elasticsearch.
    depends_on:
      setup:
        condition: service_healthy # Espera a que el servicio de configuración esté listo.
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION} # Imagen de Elasticsearch.
    volumes:
      - certs:/usr/share/elasticsearch/config/certs # Certificados SSL.
      - esdata01:/usr/share/elasticsearch/data # Almacenamiento de datos persistente.
    ports:
      - ${ES_PORT}:9200 # Expone el puerto 9200 para conexiones HTTP.
    environment:
      # Configuración del nodo y del cluster.
      - node.name=es01 # Nombre del nodo.
      - cluster.name=${CLUSTER_NAME} # Nombre del clúster.
      - discovery.type=single-node # Configuración para un clúster de un solo nodo.
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # Contraseña para el usuario "elastic".
      - bootstrap.memory_lock=true # Bloqueo de memoria para mejorar el rendimiento.
      # Configuración de seguridad y SSL para HTTP.
      - xpack.security.enabled=true # Habilita la seguridad en Elasticsearch.
      - xpack.security.http.ssl.enabled=true # Habilita SSL en HTTP.
      - xpack.security.http.ssl.key=certs/es01/es01.key # Llave SSL.
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt # Certificado SSL.
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt # CA para validar conexiones.
      # Configuración de seguridad y SSL para transporte interno.
      - xpack.security.transport.ssl.enabled=true # Habilita SSL en transporte interno.
      - xpack.security.transport.ssl.key=certs/es01/es01.key # Llave SSL.
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt # Certificado SSL.
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt # CA para transporte interno.
      - xpack.security.transport.ssl.verification_mode=certificate # Nivel de verificación SSL.
      - xpack.license.self_generated.type=${LICENSE} # Tipo de licencia (por defecto).
      - network.host=0.0.0.0 # Permite que el nodo escuche en todas las interfaces.
    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT} # Límite de memoria asignada al contenedor.
    ulimits:
      memlock:
        soft: -1 # Bloqueo suave de memoria.
        hard: -1 # Bloqueo duro de memoria.
    healthcheck:
      # Verifica que Elasticsearch esté operativo.
      test: [ "CMD-SHELL", "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'" ]
      interval: 10s # Intervalo entre verificaciones.
      timeout: 10s # Tiempo máximo para considerar la verificación fallida.
      retries: 120 # Número de reintentos permitidos.
    networks:
      - elastic_network # Red compartida por los servicios del stack.

  kibana:
    # Servicio de Kibana para la visualización y gestión de datos en Elasticsearch.
    depends_on:
      es01:
        condition: service_healthy # Espera a que Elasticsearch esté disponible.
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION} # Imagen de Kibana.
    volumes:
      - certs:/usr/share/kibana/config/certs # Certificados SSL para Kibana.
      - kibana-data:/usr/share/kibana/data # Volumen para datos persistentes de Kibana.
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro # Archivo de configuración personalizado.
    ports:
      - ${KIBANA_PORT}:5601 # Puerto expuesto para acceder a Kibana.
    environment:
      # Configuración del servidor Kibana.
      - SERVERNAME=kibana # Nombre del servidor.
      - SERVER_HOST=0.0.0.0 # Dirección donde escucha Kibana.
      - SERVER_SSL_ENABLED=true # Habilita SSL en el servidor Kibana.
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana/kibana.crt # Certificado SSL del servidor.
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana/kibana.key # Llave SSL del servidor.

      # Configuración de conexión a Elasticsearch.
      - ELASTICSEARCH_HOSTS=https://es01:9200 # Dirección de Elasticsearch.
      - ELASTICSEARCH_USERNAME=kibana_system # Usuario para conectarse a Elasticsearch.
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD} # Contraseña para el usuario.
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt # CA para validar la conexión.
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate # Modo de verificación SSL.

      # Claves de cifrado para funciones de seguridad en Kibana.
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY} # Clave para objetos cifrados.
      - XPACK_SECURITY_ENCRYPTIONKEY=${SECURITY_ENCRYPTIONKEY} # Clave para funciones de seguridad.
      - XPACK_REPORTING_ENCRYPTIONKEY=${REPORTING_ENCRYPTIONKEY} # Clave para reportes.

    deploy:
      resources:
        limits:
          memory: ${MEM_LIMIT} # Límite de memoria asignada al contenedor.
    ulimits:
      memlock:
        soft: -1 # Bloqueo suave de memoria.
        hard: -1 # Bloqueo duro de memoria.
    healthcheck:
      # Verifica que Kibana esté operativo.
      test: [ "CMD-SHELL", "curl -s --cacert /usr/share/kibana/config/certs/ca/ca.crt https://localhost:5601/api/status | grep -q '\"level\":\"available\"'" ]
      interval: 10s # Intervalo entre verificaciones.
      timeout: 10s # Tiempo máximo para considerar la verificación fallida.
      retries: 120 # Número de reintentos permitidos.
    networks:
      - elastic_network # Red compartida por los servicios del stack.

  nginx-app:
    # Servicio de Nginx como aplicación de ejemplo.
    build:
      context: ./nginx-app # Ruta donde se encuentra el Dockerfile.
    ports:
      - "8080:80" # Mapea el puerto 80 del contenedor al puerto 8080 del host.
    volumes:
      - nginx-data:/var/log/nginx # Volumen para los logs.
      - ./nginx-app/nginx.conf:/etc/nginx/nginx.conf:ro # Archivo de configuración personalizado.
    networks:
      - elastic_network # Red compartida por los servicios del stack.

  fleet-server:
    # Servicio para Fleet Server, responsable de gestionar agentes Elastic.
    depends_on:
      kibana:
        condition: service_healthy # Espera a que Kibana esté disponible.
    image: docker.elastic.co/elastic-agent/elastic-agent:${STACK_VERSION} # Imagen del agente Elastic.
    restart: always # Reinicia el contenedor automáticamente si falla.
    user: root # Ejecutar como usuario root.
    ports:
      - ${FLEET_SERVER_PORT}:8220 # Expone el puerto 8220 para el servidor Fleet.
    environment:
      # Configuración de certificados y conexión.
      - SSL_CERTIFICATE_AUTHORITIES=/usr/share/elastic-agent/certs/ca/ca.crt # CA para validación.
      - CERTIFICATE_AUTHORITIES=/usr/share/elastic-agent/certs/ca/ca.crt # Certificados de autoridad.
      - FLEET_CA=/usr/share/elastic-agent/certs/ca/ca.crt # CA para el servidor Fleet.
      - FLEET_SERVER_CERT=/usr/share/elastic-agent/certs/fleet-server/fleet-server.crt # Certificado del servidor Fleet.
      - FLEET_SERVER_CERT_KEY=/usr/share/elastic-agent/certs/fleet-server/fleet-server.key # Llave del servidor Fleet.

      # Configuración de Fleet Server.
      - FLEET_INSECURE=true # Permite conexiones inseguras durante el desarrollo.
      - FLEET_SERVER_ELASTICSEARCH_CA=/usr/share/elastic-agent/certs/ca/ca.crt # CA para Elasticsearch.
      - FLEET_SERVER_ELASTICSEARCH_SSL_CERTIFICATE=/usr/share/elastic-agent/certs/es01/es01.crt # Certificado de Elasticsearch.
      - FLEET_SERVER_ELASTICSEARCH_SSL_KEY=/usr/share/elastic-agent/certs/es01/es01.key # Llave de Elasticsearch.
      - FLEET_SERVER_ELASTICSEARCH_HOST=https://es01:9200 # Host de Elasticsearch.
      - FLEET_SERVER_ELASTICSEARCH_INSECURE=true # Permite conexiones inseguras a Elasticsearch.
      - FLEET_SERVER_ENABLE=true # Habilita el servidor Fleet.
      - FLEET_SERVER_POLICY_ID=fleet-server-policy # ID de la política asignada al servidor Fleet.
      - FLEET_URL=https://fleet-server:8220 # URL del servidor Fleet.

      # Configuración de Kibana.
      - KIBANA_FLEET_CA=/usr/share/elastic-agent/certs/ca/ca.crt # CA para Kibana.
      - KIBANA_FLEET_USERNAME=elastic # Usuario para autenticación con Kibana.
      - KIBANA_FLEET_PASSWORD=${ELASTIC_PASSWORD} # Contraseña del usuario.
      - KIBANA_HOST=https://kibana:5601 # Dirección de Kibana.

      # Nivel de registro de logs.
      - LOG_LEVEL=debug # Nivel de detalle para los logs.
    volumes:
      - certs:/usr/share/elastic-agent/certs # Certificados compartidos.
      - fleet-server-data:/usr/share/elastic-agent # Volumen para datos persistentes del servidor Fleet.
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
        # Este volumen proporciona acceso de solo lectura a los metadatos y logs de los contenedores de Docker
        # en el sistema host. Es útil para monitorear actividades y estados de los contenedores.
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
        # Permite al agente interactuar con el daemon de Docker en el sistema host para recopilar información
        # sobre los contenedores en ejecución. Esto incluye la supervisión de métricas y eventos en tiempo real.
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
        # Da acceso al sistema de control de grupos (cgroups) en el host. Los cgroups se utilizan para obtener
        # información sobre el uso de recursos como CPU, memoria y red, asignados a los contenedores.
      - "/proc:/hostfs/proc:ro"
        # Proporciona acceso al sistema de archivos proc del host, que contiene información en tiempo real sobre
        # los procesos y el estado del sistema. Es crucial para supervisar procesos dentro y fuera de los contenedores.
      - "/:/hostfs:ro"
        # Monta todo el sistema de archivos del host en modo de solo lectura. Esto permite al agente acceder a
        # configuraciones del sistema, logs y otros datos necesarios para monitorear el host y los contenedores.
    healthcheck:
      test: [ "CMD-SHELL", "curl -s --fail --cacert /usr/share/elastic-agent/certs/ca/ca.crt https://localhost:8220/api/status || exit 1" ]
      interval: 10s # Verifica cada 10 segundos.
      timeout: 5s # Tiempo máximo de espera para una respuesta.
      retries: 5 # Número de reintentos antes de marcar como no saludable.
    networks:
      - elastic_network # Red compartida por los servicios del stack.

  nginx-agent:
    # Agente Elastic para monitorear la aplicación Nginx.
    depends_on:
      fleet-server:
        condition: service_healthy # Espera a que el servidor Fleet esté disponible.
    image: docker.elastic.co/elastic-agent/elastic-agent:${STACK_VERSION} # Imagen del agente Elastic.
    restart: always # Reinicia automáticamente si falla.
    user: root # Ejecutar como usuario root.
    environment:
      # Configuración de Elasticsearch.
      - ELASTICSEARCH_HOSTS=["https://es01:9200"] # Dirección de Elasticsearch.
      - ELASTICSEARCH_USERNAME=elastic # Usuario para autenticación.
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD} # Contraseña del usuario.
      - ELASTICSEARCH_CA=/usr/share/elastic-agent/certs/ca/ca.crt # CA para validar conexiones.
      # Configuración de SSL.
      - SSL_CERTIFICATE=/usr/share/elastic-agent/certs/es01/es01.crt # Certificado SSL.
      - SSL_KEY=/usr/share/elastic-agent/certs/es01/es01.key # Llave SSL.
      - SSL_CERTIFICATE_AUTHORITIES=["/usr/share/elastic-agent/certs/ca/ca.crt"] # Autoridades de certificado.
      # Configuración de Kibana.
      - KIBANA_HOST=https://kibana:5601 # Dirección de Kibana.
      - KIBANA_USERNAME=elastic # Usuario para autenticación.
      - KIBANA_PASSWORD=${KIBANA_PASSWORD} # Contraseña del usuario.
      - KIBANA_CA=/usr/share/elastic-agent/certs/ca/ca.crt # CA para validar conexiones.
      # Configuración de Fleet.
      - FLEET_CA=/usr/share/elastic-agent/certs/ca/ca.crt # CA para Fleet.
      - FLEET_ENROLL=1 # Habilita el registro automático del agente.
      - FLEET_ENROLLMENT_TOKEN=${FLEET_ENROLLMENT_TOKEN} # Token de registro de Fleet.
      - FLEET_URL=https://fleet-server:8220 # Dirección del servidor Fleet.
      - ELASTIC_AGENT_CERT=/usr/share/elastic-agent/certs/es01/es01.crt # Certificado del agente.
      - ELASTIC_AGENT_CERT_KEY=/usr/share/elastic-agent/certs/es01/es01.key # Llave del agente.
      # Nivel de registro de logs.
      - LOG_LEVEL=debug # Nivel de detalle para los logs.

    volumes:
      # Volúmenes para acceso compartido.
      - certs:/usr/share/elastic-agent/certs # Certificados compartidos.
      - nginx-data:/var/log/nginx # Logs de la aplicación Nginx.
      - nginx-agent-data:/usr/share/elastic-agent # Datos persistentes del agente.
      - suricata-logs:/var/log/suricata # Logs de Suricata.
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
        # Este volumen proporciona acceso de solo lectura a los metadatos y logs de los contenedores de Docker
        # en el sistema host. Es útil para monitorear actividades y estados de los contenedores.
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
        # Permite al agente interactuar con el daemon de Docker en el sistema host para recopilar información
        # sobre los contenedores en ejecución. Esto incluye la supervisión de métricas y eventos en tiempo real.
      - "/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro"
        # Da acceso al sistema de control de grupos (cgroups) en el host. Los cgroups se utilizan para obtener
        # información sobre el uso de recursos como CPU, memoria y red, asignados a los contenedores.
      - "/proc:/hostfs/proc:ro"
        # Proporciona acceso al sistema de archivos proc del host, que contiene información en tiempo real sobre
        # los procesos y el estado del sistema. Es crucial para supervisar procesos dentro y fuera de los contenedores.
      - "/:/hostfs:ro"
        # Monta todo el sistema de archivos del host en modo de solo lectura. Esto permite al agente acceder a
        # configuraciones del sistema, logs y otros datos necesarios para monitorear el host y los contenedores.
    networks:
      - elastic_network # Red compartida por los servicios del stack.

  suricata:
    build:
      context: ./suricata # Ruta donde se encuentra el Dockerfile y cualquier archivo adicional (scripts, configuraciones, reglas, etc.).
    container_name: suricata # Nombre del contenedor asignado como "suricata" para facilitar la identificación.
    restart: always # Reinicia el contenedor automáticamente si se detiene por cualquier motivo.
    network_mode: "host" # Conecta el contenedor directamente a la red del host, lo que permite a Suricata monitorear todas las interfaces y el tráfico.
    cap_add:
      # Agrega capacidades especiales al contenedor para poder capturar tráfico de red y funcionar correctamente.
      - NET_ADMIN # Permite realizar operaciones de administración de red (requerido para captura de paquetes).
      - NET_RAW # Permite acceder al tráfico de red bruto.
      - SYS_NICE # Permite ajustar las prioridades de los hilos para optimizar el rendimiento de Suricata.
    volumes:
      - suricata-logs:/var/log/suricata # Monta un volumen persistente donde se almacenarán los logs de Suricata (por ejemplo, eve.json).
    environment:
      - SURICATA_UPDATE_ENABLED=true
      - NGINX_INTERFACE=${NGINX_INTERFACE}

volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  kibana-data:
    driver: local
  nginx-data:
    driver: local
  fleet-server-data:
    driver: local
  nginx-agent-data:
    driver: local
  suricata-logs:
    driver: local

#El driver bridge crea una red virtual privada para los contenedores que están conectados a ella.
#Esta red está aislada del sistema host y de otras redes de Docker,
# a menos que configuremos explícitamente conexiones hacia el exterior.
networks:
  elastic_network:
    driver: bridge
